language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run cover
after_success: npm run coveralls
deploy:
  provider: npm
  email: jp@theqrl.org
  api_key:
    secure: bzGNHoDOVL8kSjrwfVGgso7SyndND4vfQjcHx6xTCcFVcDy/d3o/xIsoBy0Un2GOfhaIxRhYswdIEtHN5x6DKAUBIbICBsVnszVIX5/sDogxb2fuptEDSbUQ6qdA/n6Au8rtK4ScYPh8lqQal71GeyYpk7AVCo35A8m3Z5scylmrPQXX56Ht9Yk7HWjAV6YaffzR5zW676+xHEkf2oORAK0NInfsy+dONg52sb540RYrhkJouVIrHMe6HHEq97FyEjR2wO/Qwz5wbrDhDUYEbgk2Ua/JM1mS2fyS98dwm9TMLR334Wscvz6BtgUgYYIWW4BAX5MW3lDeP3keZWwdBT/9jqL+NoZtUhmK+4+jTvPkcYW1yB+OLFGJpmpu1qsx2sVVsS9bLuDHlq0HweSuF5Jy9q+un7I4SkbgTro6ZcSdDxJ3mTP6c5dsIEzs7tX+i6eDtlTmpNafVK2Swtd61YAv9flvrX2Ap7JhUbV/MrC+FyGRSw5GWwYK5h5lwr0HslZXga7cjbCySX8wuiEKPCdvtYPeTA8QIzTkFhY/VVtmv8vyIEu3qn+k1O0VHoWXaoFJRsfJNxbGiYJ1HZ/dpNyt62WAS3gUUwkgy710ajgYhBpHJmJHOhwy1hieO08HCvPuB46L4g08y6df3ZHfEVE7CbeYyGmMB24WBTjAnK4=
  on:
    tags: true
    branch: master
